import type { CopyDict } from '../../copy';

// Vocabulary from docs/THEMES.md §2. Anything missing falls back to Classic.
export const copy: Partial<CopyDict> = {
  'app.today': 'Briefing',
  'task.singular': 'Mission',
  'task.plural': 'Missions',
  'task.complete': 'Complete',
  'task.completeToast': 'Mission complete!',
  'task.waiting': 'On standby since {day}',
  'task.skip': 'Stand down',
  'member.singular': 'Hero',
  'member.plural': 'Heroes',
  'household.name': 'Squad',
  'meter.name': 'Squad Charge',
  'meter.full': 'Charged!',
  'streak.name': 'Deployments',
  'stuff.name': 'Loadout',
  'plans.name': 'Ops',
  'lists.toBuy': 'Requisitions',
  'badge.singular': 'Commendation',
  'badge.plural': 'Commendations',
  'level.up': 'Rank up!',
  'coins.name': 'Credits',
  'shop.name': 'Supply shop',
  'deed.logFix': 'Log a field repair',

  'nav.today': 'Briefing',
  'nav.stuff': 'Loadout',
  'nav.plans': 'Ops',
  'today.greeting.morning': 'Morning, hero',
  'today.greeting.afternoon': 'Welcome back, hero',
  'today.greeting.evening': 'Evening, hero',
  'today.dueHeading': 'Active missions',
  'today.waitingHeading': 'On standby',
  'today.allClear': 'All missions clear',
  'today.allClearBody': 'Nothing on the board. Rest up, or scout what’s ahead.',
  'today.zone': 'Today’s sector: {zone}',
  'today.catchUp': 'Mission debrief',
  'today.catchUpHint': 'Log missions from the last week',
  'today.addTask': 'New mission',
  'task.skippedToast': 'Stood down. All good.',
  'task.new': 'New mission',
  'task.editTitle': 'Edit mission',
  'catchUp.title': 'Mission debrief',
  'catchUp.body': 'Check off anything your squad handled this week and pick the day.',
  'catchUp.empty': 'Debrief complete. Nothing to log!',
  'upcoming.title': 'Incoming',
  'history.title': 'Mission log',
  'me.title': 'Hero',
  'setup.themeTitle': 'Choose your lobby',
};
