/**
 * The full Classic dictionary. It is also the fallback for every other theme:
 * packs override only the keys they want to change.
 *
 * Variables use {braces}. Keep the tone short, warm, and never shaming.
 */
export const classicCopy = {
  // --- Shared theme vocabulary (docs/THEMES.md) ---
  'app.today': 'Today',
  'task.singular': 'Task',
  'task.plural': 'Tasks',
  'task.complete': 'Done',
  'task.completeToast': 'Nice, that’s done!',
  'task.waiting': 'Waiting since {day}',
  'task.skip': 'Skip',
  'area.singular': 'Area',
  'area.plural': 'Areas',
  'member.singular': 'Member',
  'member.plural': 'Members',
  'household.name': 'Household',
  'meter.name': 'Weekly goal',
  'meter.full': 'Goal reached!',
  'streak.name': 'Active weeks',
  'stuff.name': 'Stuff',
  'plans.name': 'Plans',
  'lists.name': 'Lists',
  'lists.toBuy': 'To buy',
  'badge.singular': 'Badge',
  'badge.plural': 'Badges',
  'level.up': 'Level up!',
  'level.label': 'Lv {level} · {title}',
  'coins.name': 'Coins',
  'shop.name': 'Reward shop',
  'deed.logFix': 'Log a fix',

  // --- App shell ---
  'app.name': 'Spawnpoint',
  'nav.today': 'Today',
  'nav.lists': 'Lists',
  'nav.stuff': 'Stuff',
  'nav.plans': 'Plans',
  'nav.me': 'Me',
  'nav.scan': 'Scan',
  'nav.main': 'Main',
  'common.back': 'Back',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.save': 'Save',
  'common.saved': 'Saved',
  'common.next': 'Next',
  'common.done': 'Done',
  'common.undo': 'Undo',
  'common.copy': 'Copy',
  'common.copied': 'Copied!',
  'common.share': 'Share',
  'common.loading': 'Loading…',
  'common.error': 'Something went sideways. Try again?',
  'common.retry': 'Try again',
  'common.edit': 'Edit',
  'common.delete': 'Delete',
  'common.archive': 'Archive',
  'common.add': 'Add',
  'common.showMore': 'Show {count} more',
  'common.showLess': 'Show less',
  'common.optional': 'optional',
  'common.comingSoon': 'Coming soon',
  'common.comingSoonBody': 'This part of the app is on its way. For now, everything else works.',
  'common.anyone': 'Anyone',
  'common.you': 'You',

  // --- Days ---
  'day.today': 'Today',
  'day.yesterday': 'Yesterday',
  'day.daysAgo': '{count} days ago',
  'day.pick': 'Pick a date',
  'day.tomorrow': 'Tomorrow',

  // --- Auth and onboarding ---
  'auth.title': 'Welcome home',
  'auth.subtitle': 'Chores, lists, stuff, and plans for your household, all in one place.',
  'auth.google': 'Continue with Google',
  'auth.devTitle': 'Dev sign-in',
  'auth.devHint': 'Local development only. Uses the fictional seed accounts.',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.signIn': 'Sign in',
  'auth.signOut': 'Sign out',
  'auth.finishing': 'Signing you in…',
  'auth.privacyNote': 'We only ask Google for your name and email.',
  'invite.needTitle': 'You’ll need an invite',
  'invite.needBody':
    'Spawnpoint is invite-only. Ask someone in your household for a link, or start a new household with an invite from whoever runs this site.',
  'invite.haveLink': 'I have an invite link',
  'invite.startHousehold': 'Start a household',
  'invite.pasteLabel': 'Invite link or code',
  'invite.pastePlaceholder': 'Paste the link or code',
  'invite.go': 'Continue',
  'invite.checking': 'Checking your invite…',
  'invite.invalid': 'That invite doesn’t work. It may have expired or already been used.',
  'invite.rateLimited': 'Too many tries. Take a breather and try again in a bit.',
  'invite.alreadyMember': 'You’re already in a household.',
  'invite.startCodeHint': 'Starting a household needs an invite code from whoever runs this site.',
  'invite.joinTitle': 'Join {household}',
  'invite.joinBody': 'You’ve been invited to join {household}. Pick how you’ll show up.',
  'invite.joinCta': 'Join household',
  'invite.startTitle': 'Let’s set up your home',
  'invite.startBody': 'Your invite is good to go. This takes about two minutes.',
  'invite.signInFirst': 'Sign in to use this invite',

  // --- Setup wizard ---
  'setup.step': 'Step {n} of {total}',
  'setup.nameTitle': 'Name your household',
  'setup.nameLabel': 'Household name',
  'setup.namePlaceholder': 'The Burrow',
  'setup.timezoneLabel': 'Time zone',
  'setup.timezoneHint': 'Days start and end in this time zone for everyone.',
  'setup.youTitle': 'How should you show up?',
  'setup.displayName': 'Your name',
  'setup.avatar': 'Avatar',
  'setup.color': 'Color',
  'setup.themeTitle': 'Pick a look',
  'setup.themeBody':
    'This becomes the household default. Everyone can pick their own later, and it’s the same data underneath.',
  'setup.areasTitle': 'Where do things happen?',
  'setup.areasBody': 'Start from a template. You can rename, add, or remove areas any time.',
  'setup.template.house': 'House',
  'setup.template.apartment': 'Apartment',
  'setup.template.custom': 'Custom',
  'setup.addArea': 'Add an area',
  'setup.modulesTitle': 'What will you use?',
  'setup.modulesBody': 'Turn parts of the app on or off. You can change this later.',
  'setup.tasksTitle': 'Starter tasks',
  'setup.tasksBody': 'Pick what fits your home. Everything is editable later.',
  'setup.tasksCount': '{count} picked',
  'setup.create': 'Create household',
  'setup.creating': 'Setting things up…',
  'setup.inviteTitle': 'Invite your people',
  'setup.inviteBody':
    'Share this link with your partner or housemates. It works once and expires in 7 days.',
  'setup.inviteCreate': 'Make an invite link',
  'setup.finish': 'Go to Today',

  // --- Starter library sections ---
  'library.section.kitchen': 'Kitchen',
  'library.section.living': 'Living areas and office',
  'library.section.bedrooms': 'Bedrooms',
  'library.section.bathrooms': 'Bathrooms',
  'library.section.laundry': 'Laundry',
  'library.section.pets': 'Pets',
  'library.section.pool': 'Pool',
  'library.section.yard': 'Yard, driveway, side yard',
  'library.section.systems': 'Systems and safety',

  // --- Member colors ---
  'color.sky': 'Sky',
  'color.mint': 'Mint',
  'color.peach': 'Peach',
  'color.lilac': 'Lilac',
  'color.lemon': 'Lemon',
  'color.rose': 'Rose',
  'color.sage': 'Sage',
  'color.sand': 'Sand',

  // --- Privacy and terms (public pages) ---
  'legal.privacyTitle': 'Privacy',
  'legal.termsTitle': 'Terms',
  'legal.privacyLink': 'Privacy',
  'legal.termsLink': 'Terms',
  'legal.updated': 'Last updated: {date}',
  'legal.runBy': 'This copy of Spawnpoint is run by {name}.',
  'legal.runByUnknown':
    'This copy of Spawnpoint is run by an independent operator: the person who invited you.',
  'legal.openSource':
    'Spawnpoint is open-source software. Each copy is run by its own operator, not by the people who wrote the software.',
  'legal.p.googleTitle': 'What we get from Google',
  'legal.p.google':
    'When you sign in with Google, we receive only your name, email address, and profile picture link (the basic openid, email, and profile permissions). We never see your Google password, and we can’t read your Gmail, Drive, Calendar, or anything else in your Google account.',
  'legal.p.useTitle': 'How that information is used',
  'legal.p.use':
    'Your email is used to sign you in and to check whether you’re allowed to run this copy. Your Google name is only a suggestion for your display name, which you choose yourself. Google user data is used only to provide the app, never for advertising, never sold, and never shared with anyone else.',
  'legal.p.storedTitle': 'What’s stored',
  'legal.p.stored':
    'Your account (email and sign-in records), your household membership, your display name, avatar, color, and theme, and what your household adds: areas, tasks, and who did what and when.',
  'legal.p.whoTitle': 'Who can see it',
  'legal.p.who':
    'Only members of your household can see your household’s data. Other households can’t, and the database enforces this. Your personal levels and coins, when they arrive, are visible only to you. The operator of this copy can technically access the database, but the app gives them no way to browse household content: their operator page shows only counts and storage sizes.',
  'legal.p.whereTitle': 'Where it lives',
  'legal.p.where':
    'Data is stored with Supabase (database and sign-in) and the app is served by Netlify. There are no ads and no third-party analytics.',
  'legal.p.controlTitle': 'Your choices',
  'legal.p.control':
    'You can leave your household at any time in Household settings. To delete your account or your household’s data, ask the operator of this copy; self-serve export and deletion are coming. You can also remove Spawnpoint’s access at any time in your Google Account under Security, Third-party apps & services.',
  'legal.p.contactTitle': 'Questions',
  'legal.p.contact': 'Contact the operator of this copy, the person who invited you.',
  'legal.t.use':
    'Spawnpoint is a free tool for households to share chores and home information. It’s provided as is, without warranties, by the operator of this copy.',
  'legal.t.invite':
    'Access is by invitation. Please use it only for your own household, and don’t upload anything you don’t have the right to share or anything illegal.',
  'legal.t.availability':
    'The operator may change or stop running this copy at any time. Keep your own copies of important documents.',
  'legal.t.privacy': 'How your information is handled is described in the Privacy page.',

  // --- Modules ---
  'module.chores': 'Chores',
  'module.lists': 'Lists',
  'module.stuff': 'Stuff',
  'module.plans': 'Plans',
  'module.pantry': 'Pantry',
  'module.rewards': 'Levels and badges',
  'module.calendar': 'Calendar',

  // --- Today ---
  'today.greeting.morning': 'Good morning',
  'today.greeting.afternoon': 'Good afternoon',
  'today.greeting.evening': 'Good evening',
  'today.dueHeading': 'Up today',
  'today.waitingHeading': 'Still waiting',
  'today.allClear': 'All clear for today',
  'today.allClearBody': 'Nothing’s due. Enjoy it, or peek at what’s coming up.',
  'today.zone': 'Today’s zone: {zone}',
  'today.catchUp': 'What got done?',
  'today.catchUpHint': 'Log things from the last week',
  'today.addTask': 'Add a task',
  'today.filterAll': 'Everyone',
  'today.filterMine': 'Mine',
  'today.thisMonth': 'This month',
  'today.meterBody': '{value} of {target} this week',

  // --- Task actions ---
  'task.moreActions': 'More options for {task}',
  'task.markDone': 'Mark {task} done',
  'task.doneWhen': 'When was it done?',
  'task.doneBy': 'Who did it?',
  'task.quantity': 'How many {unit}?',
  'task.skipReason': 'Reason',
  'task.skipReasonPlaceholder': 'Away this week',
  'task.skipConfirm': 'Skip this one',
  'task.skippedToast': 'Skipped. No worries.',
  'task.logIt': 'Log it',
  'task.loggedFor': 'Logged for {name}',
  'task.assignedTo': 'For {name}',
  'task.effort': 'Effort',
  'task.priority': 'Priority',
  'task.priority.low': 'Low',
  'task.priority.normal': 'Normal',
  'task.priority.high': 'High',
  'task.ifMissed': 'If it’s missed',
  'task.ifMissed.carry': 'Keep it on Today',
  'task.ifMissed.let_go': 'Let it go quietly',
  'task.new': 'New task',
  'task.editTitle': 'Edit task',
  'task.title': 'Title',
  'task.notes': 'Notes',
  'task.location': 'Where',
  'task.noLocation': 'Anywhere',
  'task.assignee': 'Who usually does it',
  'task.schedule': 'How often',
  'task.startOn': 'Starting',
  'task.unit': 'Count something (optional)',
  'task.unitPlaceholder': 'valves, filters…',
  'task.deed': 'Linked deed',
  'task.noDeed': 'None',
  'task.archive': 'Archive task',
  'task.archived': 'Task archived',
  'task.saved': 'Task saved',
  'task.nextDue': 'Next: {day}',

  // --- Schedules ---
  'schedule.daily': 'Every day',
  'schedule.every_n_days': 'Every {n} days',
  'schedule.every_n_days.one': 'Every day',
  'schedule.weekly_on': 'Weekly on {days}',
  'schedule.monthly_day': 'Monthly on the {day}',
  'schedule.monthly_nth': 'Monthly on the {nth} {weekday}',
  'schedule.yearly_in': 'Any time in {months}',
  'schedule.type.daily': 'Daily',
  'schedule.type.every_n_days': 'Every N days',
  'schedule.type.weekly_on': 'Weekly',
  'schedule.type.monthly_on': 'Monthly',
  'schedule.type.yearly_in': 'Yearly',
  'schedule.floatingHint': 'Counts from the last time it was done.',
  'schedule.nth.1': 'first',
  'schedule.nth.2': 'second',
  'schedule.nth.3': 'third',
  'schedule.nth.4': 'fourth',
  'schedule.nth.-1': 'last',
  'schedule.byDay': 'Day of month',
  'schedule.byWeekday': 'A weekday',

  // --- Catch-up ---
  'catchUp.title': 'What got done?',
  'catchUp.body': 'Tick anything that happened in the last week and pick the day.',
  'catchUp.empty': 'Nothing to catch up on. You’re all set!',
  'catchUp.submit': 'Log {count}',
  'catchUp.submitted': 'Logged {count}. Thanks!',
  'catchUp.since': 'Since {day}',

  // --- Areas, upcoming, history ---
  'areas.title': 'Areas',
  'areas.freshness': 'Freshness',
  'areas.freshPercent': '{percent}% fresh',
  'areas.noTasks': 'No tasks here yet',
  'areas.tasksHere': 'Tasks here',
  'areas.everywhere': 'Around the home',
  'upcoming.title': 'Upcoming',
  'upcoming.body': 'The next 7 days',
  'upcoming.nothing': 'Nothing planned',
  'history.title': 'History',
  'history.allAreas': 'All areas',
  'history.from': 'From',
  'history.to': 'To',
  'history.empty': 'Nothing logged in this range yet.',
  'history.entry': '{name} · {task}',
  'history.skipped': 'skipped',
  'history.loggedBy': 'logged by {name}',

  // --- Me and settings ---
  'me.title': 'Me',
  'me.more': 'More',
  'me.rewardsSoon': 'Levels, badges, and your reward shop arrive soon.',
  'me.personal': 'Personal settings',
  'me.household': 'Household settings',
  'settings.personalTitle': 'Personal settings',
  'settings.householdTitle': 'Household settings',
  'settings.theme': 'Theme',
  'settings.followHousehold': 'Follow household ({theme})',
  'settings.mode': 'Light or dark',
  'settings.mode.system': 'System',
  'settings.mode.light': 'Light',
  'settings.mode.dark': 'Dark',
  'settings.profile': 'Profile',
  'settings.householdName': 'Name',
  'settings.timezone': 'Time zone',
  'settings.defaultTheme': 'Default theme',
  'settings.weeklyTarget': 'Weekly goal target',
  'settings.modules': 'Modules',
  'settings.members': 'Members',
  'settings.owner': 'Owner',
  'settings.makeOwner': 'Make owner',
  'settings.remove': 'Remove',
  'settings.removed': '{name} was removed',
  'settings.invites': 'Invite links',
  'settings.newInvite': 'New invite link',
  'settings.revoke': 'Revoke',
  'settings.expires': 'Expires {day}',
  'settings.zoneRotation': 'Zone rotation',
  'settings.zoneRotationBody': 'Give each weekday an area. Weekly tasks there move to that day.',
  'settings.ownerOnly': 'Only the household owner can change these.',
  'settings.areas': 'Areas and zones',
  'settings.addZone': 'Add zone',
  'settings.addArea': 'Add area',
  'settings.addSpot': 'Add spot',
  'settings.leave': 'Leave household',
  'settings.locationName': 'Name',

  // --- Operator ---
  'operator.title': 'Operator',
  'operator.body': 'Counts and sizes only. Household content is never shown here.',
  'operator.households': 'Households',
  'operator.members': 'Members',
  'operator.storage': 'Storage per household',
  'operator.invites': 'Household invites',
  'operator.newInvite': 'New household invite',
  'operator.label': 'Label (just for you)',
  'operator.linkOnce': 'Copy this link now. It won’t be shown again.',
  'operator.status.active': 'Active',
  'operator.status.used': 'Used',
  'operator.status.expired': 'Expired',
  'operator.status.revoked': 'Revoked',
  'operator.notOperator': 'This page is for whoever runs this site.',

  // --- Styleguide ---
  'styleguide.title': 'Styleguide',
} as const;

export type CopyKey = keyof typeof classicCopy;
export type CopyDict = Record<CopyKey, string>;
