/**
 * The full Classic dictionary. It is also the fallback for every other theme:
 * packs override only the keys they want to change.
 *
 * Variables use {braces}. Keep the tone short, warm, and never shaming.
 */
export const classicCopy = {
  // --- Shared theme vocabulary (docs/THEMES.md) ---
  'app.today': 'Today',
  'task.singular': 'Task',
  'task.plural': 'Tasks',
  'task.complete': 'Done',
  'task.completeToast': 'Nice, that’s done!',
  'task.waiting': 'Waiting since {day}',
  'task.skip': 'Skip',
  'area.singular': 'Area',
  'area.plural': 'Areas',
  'member.singular': 'Member',
  'member.plural': 'Members',
  'household.name': 'Household',
  'meter.name': 'Weekly goal',
  'meter.full': 'Goal reached!',
  'streak.name': 'Active weeks',
  'stuff.name': 'Stuff',
  'plans.name': 'Plans',
  'lists.name': 'Lists',
  'lists.toBuy': 'To buy',
  'lists.groceries': 'Groceries',
  'lists.todo': 'To-do',
  'lists.new': 'New list',
  'lists.newName': 'List name',
  'lists.newPlaceholder': 'Packing list',
  'lists.icon': 'Icon',
  'lists.iconOption': 'Icon {n}',
  'lists.create': 'Create list',
  'lists.left': '{count} to go',
  'lists.nothingLeft': 'All clear',
  'lists.empty': 'Nothing here yet',
  'lists.emptyBody': 'Add the first item at the top.',
  'lists.allDone': 'Everything’s checked off. Nice.',
  'lists.addPlaceholder': 'Add an item',
  'lists.addLabel': 'Add to {list}',
  'lists.itemDeleted': 'Removed {name}',
  'lists.cleared': 'Cleared {count}',
  'lists.check': 'Check off {name}',
  'lists.uncheck': 'Uncheck {name}',
  'lists.open': 'Edit {name}',
  'lists.move': 'Move {name}. Drag, or use the arrow keys.',
  'lists.moved': 'Moved',
  'lists.moveUp': 'Move up',
  'lists.moveDown': 'Move down',
  'lists.doneSection': 'Done · {count}',
  'lists.clearDone': 'Clear done',
  'lists.rename': 'Rename list',
  'lists.archive': 'Archive list',
  'lists.archived': 'List archived',
  'lists.itemName': 'Name',
  'lists.notes': 'Notes',
  'lists.notFound': 'That list isn’t here anymore.',
  'lists.swipeHint': 'Swipe right to check off, left to remove',
  'grocery.quantity': 'Quantity',
  'grocery.category': 'Aisle',
  'grocery.cat.produce': 'Produce',
  'grocery.cat.dairy': 'Dairy & eggs',
  'grocery.cat.meat': 'Meat & fish',
  'grocery.cat.bakery': 'Bakery',
  'grocery.cat.pantry': 'Pantry',
  'grocery.cat.frozen': 'Frozen',
  'grocery.cat.drinks': 'Drinks',
  'grocery.cat.household': 'Household',
  'grocery.cat.pets': 'Pets',
  'grocery.cat.other': 'Other',
  'grocery.mode': 'View',
  'grocery.listMode': 'List',
  'grocery.storeMode': 'Store',
  'grocery.inCart': 'In cart · {count}',
  'grocery.putBack': 'Take {name} out of the cart',
  'grocery.doneShopping': 'Done shopping',
  'grocery.doneToast': 'Trip saved: {count} items',
  'grocery.staples': 'Staples',
  'grocery.staplesBody': 'Things you buy again and again. Tap one to add it.',
  'grocery.staplesEmpty': 'No staples yet. Add the things you buy most.',
  'grocery.addStaple': 'Add a staple',
  'grocery.stapleName': 'Staple',
  'grocery.makeStaple': 'Keep as a staple',
  'grocery.isStaple': 'Saved as a staple',
  'grocery.onList': 'On the list',
  'grocery.removeStaple': 'Remove {name} from staples',
  'grocery.addNamed': 'Add {name}',
  'grocery.suggestions': 'Suggestions',
  'grocery.already': '{name} is already on the list',
  'toBuy.status': 'Status',
  'toBuy.status.idea': 'Idea',
  'toBuy.status.to_buy': 'To buy',
  'toBuy.status.bought': 'Bought',
  'toBuy.price': 'Target price',
  'toBuy.pricePlaceholder': '0.00',
  'toBuy.links': 'Links',
  'toBuy.linksHint': 'Paste up to 5, one per line.',
  'toBuy.linksInvalid': 'Links need to start with http:// or https://',
  'toBuy.area': 'Where it goes',
  'toBuy.noArea': 'Anywhere',
  'toBuy.markBought': 'Mark {name} bought',
  'toBuy.boughtSection': 'Bought · {count}',
  'toBuy.boughtOn': 'Bought {day}',
  'toBuy.boughtToast': 'Marked bought',
  'toBuy.stuffSoon': 'Adding bought things to Stuff arrives with the Stuff tab.',
  'todo.due': 'Due date',
  'todo.dueOn': 'Due {day}',
  'todo.dueToday': 'Due today',
  'todo.assignee': 'Who',
  'todo.discuss': 'Talk it over',
  'todo.discussHint': 'Flag it for your next household sit-down.',
  'todo.discussTag': 'Talk it over',
  'todo.mine': 'Mine',
  'todo.all': 'Everyone',
  'badge.singular': 'Badge',
  'badge.plural': 'Badges',
  'level.up': 'Level up!',
  'level.label': 'Lv {level} · {title}',
  'coins.name': 'Coins',
  'shop.name': 'Reward shop',
  'deed.logFix': 'Log a fix',

  // --- App shell ---
  'app.name': 'Spawnpoint',
  'nav.today': 'Today',
  'nav.lists': 'Lists',
  'nav.stuff': 'Stuff',
  'nav.plans': 'Plans',
  'nav.me': 'Me',
  'nav.scan': 'Scan',
  'nav.main': 'Main',
  'common.back': 'Back',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.save': 'Save',
  'common.saved': 'Saved',
  'common.next': 'Next',
  'common.done': 'Done',
  'common.undo': 'Undo',
  'common.copy': 'Copy',
  'common.copied': 'Copied!',
  'common.share': 'Share',
  'common.loading': 'Loading…',
  'common.error': 'Something went sideways. Try again?',
  'common.retry': 'Try again',
  'common.edit': 'Edit',
  'common.delete': 'Delete',
  'common.archive': 'Archive',
  'common.add': 'Add',
  'common.showMore': 'Show {count} more',
  'common.showLess': 'Show less',
  'common.optional': 'optional',
  'common.comingSoon': 'Coming soon',
  'common.comingSoonBody': 'This part of the app is on its way. For now, everything else works.',
  'common.anyone': 'Anyone',
  'common.you': 'You',

  // --- Days ---
  'day.today': 'Today',
  'day.yesterday': 'Yesterday',
  'day.daysAgo': '{count} days ago',
  'day.pick': 'Pick a date',
  'day.tomorrow': 'Tomorrow',

  // --- Auth and onboarding ---
  'auth.title': 'Welcome home',
  'auth.subtitle': 'Chores, lists, stuff, and plans for your household, all in one place.',
  'auth.google': 'Continue with Google',
  'auth.devTitle': 'Dev sign-in',
  'auth.devHint': 'Local development only. Uses the fictional seed accounts.',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.signIn': 'Sign in',
  'auth.signOut': 'Sign out',
  'auth.finishing': 'Signing you in…',
  'auth.privacyNote': 'We only ask Google for your name and email.',
  'invite.needTitle': 'You’ll need an invite',
  'invite.needBody':
    'Spawnpoint is invite-only. Ask someone in your household for a link, or start a new household with an invite from whoever runs this site.',
  'invite.haveLink': 'I have an invite link',
  'invite.startHousehold': 'Start a household',
  'invite.pasteLabel': 'Invite link or code',
  'invite.pastePlaceholder': 'Paste the link or code',
  'invite.go': 'Continue',
  'invite.checking': 'Checking your invite…',
  'invite.invalid': 'That invite doesn’t work. It may have expired or already been used.',
  'invite.rateLimited': 'Too many tries. Take a breather and try again in a bit.',
  'invite.alreadyMember': 'You’re already in a household.',
  'invite.startCodeHint': 'Starting a household needs an invite code from whoever runs this site.',
  'invite.joinTitle': 'Join {household}',
  'invite.joinBody': 'You’ve been invited to join {household}. Pick how you’ll show up.',
  'invite.joinCta': 'Join household',
  'invite.startTitle': 'Let’s set up your home',
  'invite.startBody': 'Your invite is good to go. This takes about two minutes.',
  'invite.signInFirst': 'Sign in to use this invite',

  // --- Setup wizard ---
  'setup.step': 'Step {n} of {total}',
  'setup.nameTitle': 'Name your household',
  'setup.nameLabel': 'Household name',
  'setup.namePlaceholder': 'The Burrow',
  'setup.timezoneLabel': 'Time zone',
  'setup.timezoneHint': 'Days start and end in this time zone for everyone.',
  'setup.youTitle': 'How should you show up?',
  'setup.displayName': 'Your name',
  'setup.avatar': 'Avatar',
  'setup.color': 'Color',
  'setup.themeTitle': 'Pick a look',
  'setup.themeBody':
    'This becomes the household default. Everyone can pick their own later, and it’s the same data underneath.',
  'setup.areasTitle': 'Where do things happen?',
  'setup.areasBody': 'Start from a template. You can rename, add, or remove areas any time.',
  'setup.template.house': 'House',
  'setup.template.apartment': 'Apartment',
  'setup.template.custom': 'Custom',
  'setup.addArea': 'Add an area',
  'setup.modulesTitle': 'What will you use?',
  'setup.modulesBody': 'Turn parts of the app on or off. You can change this later.',
  'setup.tasksTitle': 'Starter tasks',
  'setup.tasksBody': 'Pick what fits your home. Everything is editable later.',
  'setup.tasksCount': '{count} picked',
  'setup.create': 'Create household',
  'setup.creating': 'Setting things up…',
  'setup.inviteTitle': 'Invite your people',
  'setup.inviteBody':
    'Share this link with your partner or housemates. It works once and expires in 7 days.',
  'setup.inviteCreate': 'Make an invite link',
  'setup.finish': 'Go to Today',

  // --- Starter library sections ---
  'library.section.kitchen': 'Kitchen',
  'library.section.living': 'Living areas and office',
  'library.section.bedrooms': 'Bedrooms',
  'library.section.bathrooms': 'Bathrooms',
  'library.section.laundry': 'Laundry',
  'library.section.pets': 'Pets',
  'library.section.pool': 'Pool',
  'library.section.yard': 'Yard, driveway, side yard',
  'library.section.systems': 'Systems and safety',

  // --- Member colors ---
  'color.sky': 'Sky',
  'color.mint': 'Mint',
  'color.peach': 'Peach',
  'color.lilac': 'Lilac',
  'color.lemon': 'Lemon',
  'color.rose': 'Rose',
  'color.sage': 'Sage',
  'color.sand': 'Sand',

  // --- Privacy and terms (public pages) ---
  'legal.privacyTitle': 'Privacy',
  'legal.termsTitle': 'Terms',
  'legal.privacyLink': 'Privacy',
  'legal.termsLink': 'Terms',
  'legal.updated': 'Last updated: {date}',
  'legal.runBy': 'This copy of Spawnpoint is run by {name}.',
  'legal.runByUnknown':
    'This copy of Spawnpoint is run by an independent operator: the person who invited you.',
  'legal.openSource':
    'Spawnpoint is open-source software. Each copy is run by its own operator, not by the people who wrote the software.',
  'legal.p.googleTitle': 'What we get from Google',
  'legal.p.google':
    'When you sign in with Google, we receive only your name, email address, and profile picture link (the basic openid, email, and profile permissions). We never see your Google password, and we can’t read your Gmail, Drive, Calendar, or anything else in your Google account.',
  'legal.p.useTitle': 'How that information is used',
  'legal.p.use':
    'Your email is used to sign you in and to check whether you’re allowed to run this copy. Your Google name is only a suggestion for your display name, which you choose yourself. Google user data is used only to provide the app, never for advertising, never sold, and never shared with anyone else.',
  'legal.p.storedTitle': 'What’s stored',
  'legal.p.stored':
    'Your account (email and sign-in records), your household membership, your display name, avatar, color, and theme, and what your household adds: areas, tasks, and who did what and when.',
  'legal.p.whoTitle': 'Who can see it',
  'legal.p.who':
    'Only members of your household can see your household’s data. Other households can’t, and the database enforces this. Your personal levels and coins, when they arrive, are visible only to you. The operator of this copy can technically access the database, but the app gives them no way to browse household content: their operator page shows only counts and storage sizes.',
  'legal.p.whereTitle': 'Where it lives',
  'legal.p.where':
    'Data is stored with Supabase (database and sign-in) and the app is served by Netlify. There are no ads and no third-party analytics.',
  'legal.p.controlTitle': 'Your choices',
  'legal.p.control':
    'You can leave your household at any time in Household settings. To delete your account or your household’s data, ask the operator of this copy; self-serve export and deletion are coming. You can also remove Spawnpoint’s access at any time in your Google Account under Security, Third-party apps & services.',
  'legal.p.contactTitle': 'Questions',
  'legal.p.contact': 'Contact the operator of this copy, the person who invited you.',
  'legal.t.use':
    'Spawnpoint is a free tool for households to share chores and home information. It’s provided as is, without warranties, by the operator of this copy.',
  'legal.t.invite':
    'Access is by invitation. Please use it only for your own household, and don’t upload anything you don’t have the right to share or anything illegal.',
  'legal.t.availability':
    'The operator may change or stop running this copy at any time. Keep your own copies of important documents.',
  'legal.t.privacy': 'How your information is handled is described in the Privacy page.',

  // --- What's new ---
  'updates.title': 'What’s new',
  'updates.version': 'Version {version}',
  'updates.newBadge': 'New',
  'updates.dot': 'New updates',
  'updates.kind.new': 'New',
  'updates.kind.improved': 'Better',
  'updates.kind.fixed': 'Fixed',

  // --- Help, FAQ, guide mode, feedback ---
  'help.title': 'Help',
  'help.subtitle': 'Tips, answers, and a way to reach whoever runs this site.',
  'help.menu': 'Help and feedback',
  'help.guideMode': 'Guide mode',
  'help.guideModeBody': 'Show little tips around the app.',
  'help.resetTips': 'Show all tips again',
  'help.tipsReset': 'Tips are back on',
  'help.faqTitle': 'Questions people ask',
  'help.contactTitle': 'Get in touch',
  'help.contactBody':
    'Messages go privately to whoever runs this site. Your household can’t see them.',
  'help.report.bug': 'Report a bug',
  'help.report.bugBody': 'Something broke or looks wrong',
  'help.report.question': 'Ask a question',
  'help.report.questionBody': 'Not sure how something works',
  'help.report.idea': 'Suggest an idea',
  'help.report.ideaBody': 'Something you’d love to see',
  'help.q.done': 'How do I check something off?',
  'help.a.done':
    'Tap the circle next to it. That’s it. If you tapped by mistake, hit Undo in the message that pops up at the bottom. It stays for 6 seconds.',
  'help.q.backdate': 'I did it yesterday, or someone else did it. How do I log that?',
  'help.a.backdate':
    'Press and hold the task (or tap the … button). You can pick Yesterday, 2 days ago, or any date, choose who did it, and add a count if the task has one, like “10 valves”.',
  'help.q.skip': 'What if we’re skipping it this time?',
  'help.a.skip':
    'Press and hold the task and choose Skip. You can add a reason like “Away this week”. A skip counts as handled, so it won’t nag you.',
  'help.q.waiting': 'What does “Waiting since” mean?',
  'help.a.waiting':
    'Some tasks are set to stay on Today until they’re done, even if the day passes. They show once, never piled up, and the most overdue ones come first. Others quietly let go when the day ends. You choose this per task under “If it’s missed”.',
  'help.q.catchUp': 'I forgot to log a bunch of things this week.',
  'help.a.catchUp':
    'Use “What got done?” on Today. Tick everything that happened in the last week, pick the day for each, and log them all at once.',
  'help.q.freshness': 'What are the bars on Areas?',
  'help.a.freshness':
    'Freshness: the share of tasks in that area that are up to date. It’s a gentle nudge, never a score.',
  'help.q.rotation': 'What is zone rotation?',
  'help.a.rotation':
    'Give each weekday an area, like Monday for the kitchen. Weekly tasks in that area move to that day, so each day has a focus. Set it in Household settings.',
  'help.q.shopping': 'How does the grocery list work at the store?',
  'help.a.shopping':
    'Switch Groceries to Store to group items by aisle. Tap an item as it goes in the cart. When you’re done, tap Done shopping: the cart clears, and what you bought helps with suggestions next time. Tapped it too soon? Undo works for a few seconds.',
  'help.q.staples': 'We buy the same things every week. Is there a shortcut?',
  'help.a.staples':
    'Yes: staples. Open Staples on the Groceries list and add the things you always buy. One tap puts a staple back on the list, and typing a few letters suggests staples and past purchases.',
  'help.q.theme': 'How do I change the look, or switch to dark mode?',
  'help.a.theme':
    'Tap the sun or moon at the top of Me to switch between system, light, and dark. For themes, go to Me, then Personal settings. Everyone in the household can pick their own theme.',
  'help.q.invite': 'How do I add my partner or housemate?',
  'help.a.invite':
    'The household owner can make an invite link in Household settings. It works once and lasts 7 days. They open it, sign in with Google, and they’re in.',
  'help.q.install': 'Can I put it on my home screen?',
  'help.a.install':
    'Yes. On iPhone, open the site in Safari, tap Share, then Add to Home Screen. On Android, tap the ⋮ menu, then Install app. It then opens like a normal app and updates itself.',
  'help.q.private': 'Who can see my stuff?',
  'help.a.private':
    'Only people in your household. Other households can’t, and the person who runs this site only sees counts, never what’s inside. See the Privacy page for details.',
  'help.q.numbers': 'Are we being compared or scored?',
  'help.a.numbers':
    'No. There are no leaderboards and nothing is ever taken away. Levels and coins (coming soon) are visible only to you.',
  'feedback.title.bug': 'Report a bug',
  'feedback.title.question': 'Ask a question',
  'feedback.title.idea': 'Suggest an idea',
  'feedback.label.bug': 'What happened?',
  'feedback.label.question': 'Your question',
  'feedback.label.idea': 'Your idea',
  'feedback.hint.bug':
    'What you tapped, what you expected, and what you saw instead. Screenshots aren’t supported yet.',
  'feedback.hint.question': 'Ask anything about using the app.',
  'feedback.hint.idea': 'Big or small, it all helps.',
  'feedback.send': 'Send',
  'feedback.sent': 'Sent. Thank you!',
  'feedback.tooMany': 'That’s a lot of messages for one day. Try again tomorrow.',
  'feedback.privacy':
    'Goes privately to whoever runs this site, with the page you were on and the app version.',
  'feedback.yours': 'Your messages',
  'feedback.status.open': 'Sent',
  'feedback.status.done': 'Handled',
  'feedback.reply': 'Reply: {note}',
  'feedback.operatorTitle': 'Feedback',
  'feedback.operatorEmpty': 'Nothing waiting. All caught up.',
  'feedback.markDone': 'Mark handled',
  'feedback.reopen': 'Reopen',
  'feedback.notePlaceholder': 'Optional reply the sender will see',
  'feedback.showHandled': 'Show handled',
  'feedback.from': 'Household #{ref}',
  'feedback.noHousehold': 'No household yet',
  'feedback.kind.bug': 'Bug',
  'feedback.kind.question': 'Question',
  'feedback.kind.idea': 'Idea',
  'tip.label': 'Tip',
  'tip.dismiss': 'Got it',
  'tip.today.longpress':
    'Press and hold a task to log it for another day, for someone else, or to skip it.',
  'tip.today.undo': 'Tapped by mistake? Every check-off shows an Undo for 6 seconds.',
  'tip.lists.swipe':
    'Swipe an item right to check it off, or left to remove it. Drag the dots to reorder.',
  'tip.grocery.store':
    'At the store? Switch to Store to group by aisle. Checked items wait in the cart until you tap Done shopping.',
  'tip.catchUp': 'Tick what happened, pick the day, then log them all at once.',
  'tip.editor.ifMissed':
    '“Keep it on Today” is for things that really need doing. “Let it go” is for nice-to-haves that can wait for next time.',
  'tip.areas': 'Freshness shows how up to date each area is. It’s never a score.',
  'tip.rotation': 'Zone rotation gives each weekday an area. Weekly tasks there move to that day.',
  'me.modeToggle': 'Light or dark: {mode}',

  // --- Rewards (Phase 2) ---
  'rewards.progress': '{into} of {span} XP to Lv {next}',
  'rewards.totalXp': '{xp} XP total',
  'rewards.balance': '{coins} {coinsName}',
  'rewards.weeks': '{count} total',
  'rewards.run': 'Current run: {count}',
  'rewards.runNone': 'A new run starts with 3 active days this week',
  'rewards.seeAll': 'See all',
  'rewards.private': 'Only you can see your level, XP, and {coinsName}.',
  'rewards.shareCard': 'Share card',
  'rewards.shareBadges': '{count} badges earned',
  'rewards.shareSaved': 'Card saved to your downloads',
  'rewards.shareFailed': 'Couldn’t make the card. Try again?',
  'season.Q1': 'Winter',
  'season.Q2': 'Spring',
  'season.Q3': 'Summer',
  'season.Q4': 'Fall',
  'season.title': '{season} season',
  'season.body': '{done} of 10 goals. Finish 5 for this season’s badge.',
  'season.earned': 'Season badge earned!',
  'goal.days_20': 'Be active on 20 days',
  'goal.tasks_40': 'Finish 40 tasks',
  'goal.effort_15': 'Finish 15 bigger tasks',
  'goal.deeds_3': 'Log 3 deeds',
  'goal.weeks_6': 'Have 6 active weeks',
  'goal.run_3': '3 active weeks in a row',
  'goal.areas_5': 'Do tasks in 5 different areas',
  'goal.catchup_2': 'Use catch-up twice',
  'goal.fix_2': 'Log a fix twice',
  'goal.xp_1000': 'Earn 1,000 XP',
  'badges.milestones': 'Milestones',
  'badges.deeds': 'Deeds',
  'badges.tier.1': 'Bronze',
  'badges.tier.2': 'Silver',
  'badges.tier.3': 'Gold',
  'badges.tier.4': 'Platinum',
  'badges.progress': '{count} of {next}',
  'badges.progressUnit': '{count} of {next} {unit}',
  'badges.allTiers': 'Every tier earned!',
  'badges.later': 'Arrives with a later update.',
  'badges.none': 'Nothing yet. They come from doing things, never from racing anyone.',
  'badges.earnedOn': 'Earned {day}',
  'shop.balance': 'You have {coins} {coinsName}',
  'shop.private': 'Only you can see your shop.',
  'shop.redeem': 'Redeem',
  'shop.redeemFor': 'Redeem for {cost}',
  'shop.redeemed': 'Enjoy it! {name}',
  'shop.shareRedeem': 'Share with the household',
  'shop.need': '{need} more to go',
  'shop.add': 'Add a reward',
  'shop.rewardName': 'Reward',
  'shop.rewardPlaceholder': 'Sleep in Saturday',
  'shop.cost': 'Cost',
  'shop.icon': 'Icon',
  'shop.suggestions': 'Ideas to start with',
  'shop.empty': 'Your shop is empty. Add something you’d enjoy.',
  'shop.removed': 'Removed from your shop',
  'shop.remove': 'Remove {name}',
  'feed.title': 'Household feed',
  'feed.body': 'Shared moments. No scores, no rankings.',
  'feed.badge': '{name} earned {badge}',
  'feed.badgeTier': '{name} earned {tier}: {badge}',
  'feed.badgeArea': '{name} earned {badge}: {area}',
  'feed.redeem': '{name} enjoyed a reward: {icon} {reward}',
  'feed.empty': 'Nothing here yet. New badges show up here.',
  'fix.title': 'What did you fix?',
  'fix.search': 'Search',
  'fix.searchPlaceholder': 'Toilet, filter, drywall…',
  'fix.logged': 'Nice fix! Logged.',
  'fix.none': 'No match. Try another word.',
  'settings.shareBadges': 'Share my new badges with the household',
  'settings.shareBadgesBody':
    'A small celebration in the household feed. Numbers are never shared.',

  // --- Modules ---
  'module.chores': 'Chores',
  'module.lists': 'Lists',
  'module.stuff': 'Stuff',
  'module.plans': 'Plans',
  'module.pantry': 'Pantry',
  'module.rewards': 'Levels and badges',
  'module.calendar': 'Calendar',

  // --- Today ---
  'today.greeting.morning': 'Good morning',
  'today.greeting.afternoon': 'Good afternoon',
  'today.greeting.evening': 'Good evening',
  'today.dueHeading': 'Up today',
  'today.waitingHeading': 'Still waiting',
  'today.allClear': 'All clear for today',
  'today.allClearBody': 'Nothing’s due. Enjoy it, or peek at what’s coming up.',
  'today.zone': 'Today’s zone: {zone}',
  'today.catchUp': 'What got done?',
  'today.catchUpHint': 'Log things from the last week',
  'today.addTask': 'Add a task',
  'today.filterAll': 'Everyone',
  'today.filterMine': 'Mine',
  'today.thisMonth': 'This month',
  'today.meterBody': '{value} of {target} this week',

  // --- Task actions ---
  'task.moreActions': 'More options for {task}',
  'task.markDone': 'Mark {task} done',
  'task.doneWhen': 'When was it done?',
  'task.doneBy': 'Who did it?',
  'task.quantity': 'How many {unit}?',
  'task.skipReason': 'Reason',
  'task.skipReasonPlaceholder': 'Away this week',
  'task.skipConfirm': 'Skip this one',
  'task.skippedToast': 'Skipped. No worries.',
  'task.logIt': 'Log it',
  'task.loggedFor': 'Logged for {name}',
  'task.assignedTo': 'For {name}',
  'task.effort': 'Effort',
  'task.priority': 'Priority',
  'task.priority.low': 'Low',
  'task.priority.normal': 'Normal',
  'task.priority.high': 'High',
  'task.ifMissed': 'If it’s missed',
  'task.ifMissed.carry': 'Keep it on Today',
  'task.ifMissed.let_go': 'Let it go quietly',
  'task.new': 'New task',
  'task.editTitle': 'Edit task',
  'task.title': 'Title',
  'task.notes': 'Notes',
  'task.location': 'Where',
  'task.noLocation': 'Anywhere',
  'task.assignee': 'Who usually does it',
  'task.schedule': 'How often',
  'task.startOn': 'Starting',
  'task.unit': 'Count something (optional)',
  'task.unitPlaceholder': 'valves, filters…',
  'task.deed': 'Linked deed',
  'task.noDeed': 'None',
  'task.archive': 'Archive task',
  'task.archived': 'Task archived',
  'task.saved': 'Task saved',
  'task.nextDue': 'Next: {day}',

  // --- Schedules ---
  'schedule.daily': 'Every day',
  'schedule.every_n_days': 'Every {n} days',
  'schedule.every_n_days.one': 'Every day',
  'schedule.weekly_on': 'Weekly on {days}',
  'schedule.monthly_day': 'Monthly on the {day}',
  'schedule.monthly_nth': 'Monthly on the {nth} {weekday}',
  'schedule.yearly_in': 'Any time in {months}',
  'schedule.type.daily': 'Daily',
  'schedule.type.every_n_days': 'Every N days',
  'schedule.type.weekly_on': 'Weekly',
  'schedule.type.monthly_on': 'Monthly',
  'schedule.type.yearly_in': 'Yearly',
  'schedule.floatingHint': 'Counts from the last time it was done.',
  'schedule.nth.1': 'first',
  'schedule.nth.2': 'second',
  'schedule.nth.3': 'third',
  'schedule.nth.4': 'fourth',
  'schedule.nth.-1': 'last',
  'schedule.byDay': 'Day of month',
  'schedule.byWeekday': 'A weekday',

  // --- Catch-up ---
  'catchUp.title': 'What got done?',
  'catchUp.body': 'Tick anything that happened in the last week and pick the day.',
  'catchUp.empty': 'Nothing to catch up on. You’re all set!',
  'catchUp.submit': 'Log {count}',
  'catchUp.submitted': 'Logged {count}. Thanks!',
  'catchUp.since': 'Since {day}',

  // --- Areas, upcoming, history ---
  'areas.title': 'Areas',
  'areas.freshness': 'Freshness',
  'areas.freshPercent': '{percent}% fresh',
  'areas.noTasks': 'No tasks here yet',
  'areas.tasksHere': 'Tasks here',
  'areas.everywhere': 'Around the home',
  'upcoming.title': 'Upcoming',
  'upcoming.body': 'The next 7 days',
  'upcoming.nothing': 'Nothing planned',
  'history.title': 'History',
  'history.allAreas': 'All areas',
  'history.from': 'From',
  'history.to': 'To',
  'history.empty': 'Nothing logged in this range yet.',
  'history.entry': '{name} · {task}',
  'history.skipped': 'skipped',
  'history.loggedBy': 'logged by {name}',

  // --- Me and settings ---
  'me.title': 'Me',
  'me.more': 'More',
  'me.rewardsSoon': 'Levels, badges, and your reward shop arrive soon.',
  'me.personal': 'Personal settings',
  'me.household': 'Household settings',
  'settings.personalTitle': 'Personal settings',
  'settings.householdTitle': 'Household settings',
  'settings.theme': 'Theme',
  'settings.followHousehold': 'Follow household ({theme})',
  'settings.mode': 'Light or dark',
  'settings.mode.system': 'System',
  'settings.mode.light': 'Light',
  'settings.mode.dark': 'Dark',
  'settings.profile': 'Profile',
  'settings.householdName': 'Name',
  'settings.timezone': 'Time zone',
  'settings.defaultTheme': 'Default theme',
  'settings.weeklyTarget': 'Weekly goal target',
  'settings.modules': 'Modules',
  'settings.members': 'Members',
  'settings.owner': 'Owner',
  'settings.makeOwner': 'Make owner',
  'settings.remove': 'Remove',
  'settings.removed': '{name} was removed',
  'settings.invites': 'Invite links',
  'settings.newInvite': 'New invite link',
  'settings.revoke': 'Revoke',
  'settings.expires': 'Expires {day}',
  'settings.zoneRotation': 'Zone rotation',
  'settings.zoneRotationBody': 'Give each weekday an area. Weekly tasks there move to that day.',
  'settings.ownerOnly': 'Only the household owner can change these.',
  'settings.areas': 'Areas and zones',
  'settings.addZone': 'Add zone',
  'settings.addArea': 'Add area',
  'settings.addSpot': 'Add spot',
  'settings.leave': 'Leave household',
  'settings.locationName': 'Name',

  // --- Operator ---
  'operator.title': 'Operator',
  'operator.body': 'Counts and sizes only. Household content is never shown here.',
  'operator.households': 'Households',
  'operator.members': 'Members',
  'operator.storage': 'Storage per household',
  'operator.invites': 'Household invites',
  'operator.newInvite': 'New household invite',
  'operator.label': 'Label (just for you)',
  'operator.linkOnce': 'Copy this link now. It won’t be shown again.',
  'operator.status.active': 'Active',
  'operator.status.used': 'Used',
  'operator.status.expired': 'Expired',
  'operator.status.revoked': 'Revoked',
  'operator.rename': 'Rename {label}',
  'operator.createdHousehold': 'Became household #{ref}',
  'operator.labelPlaceholder': 'Who it’s for',
  'operator.notOperator': 'This page is for whoever runs this site.',

  // --- Styleguide ---
  'styleguide.title': 'Styleguide',
} as const;

export type CopyKey = keyof typeof classicCopy;
export type CopyDict = Record<CopyKey, string>;
